In [1]:
import pandas as pd

In [8]:
df = pd.read_excel(r"C:\Users\veda\OneDrive\Desktop\DataCoSupplyChainDataset.xlsx")
print(df)

            Type  Days for shipping (real)  Days for shipment (scheduled)  \
0          DEBIT                         3                              4
1       TRANSFER                         5                              4
2           CASH                         4                              4
3          DEBIT                         3                              4
4        PAYMENT                         2                              4
...          ...                       ...                            ...
180514      CASH                         4                              4
180515     DEBIT                         3                              2
180516  TRANSFER                         5                              4
180517   PAYMENT                         3                              4
180518   PAYMENT                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
0               91.250000          314.640015  Advance shipping
1             -249.089996          311.359985     Late delivery
2             -247.779999          309.720001  Shipping on time
3               22.860001          304.809998  Advance shipping
4              134.210007          298.250000  Advance shipping
...                   ...                 ...               ...
180514          40.000000          399.980011  Shipping on time
180515        -613.770019          395.980011     Late delivery
180516         141.110001          391.980011     Late delivery
180517         186.229996          387.980011  Advance shipping
180518         168.949997          383.980011  Shipping on time

        Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                        0           73  Sporting Goods        Caguas  ...
1                        1           73  Sporting Goods        Caguas  ...
2                        0           73  Sporting Goods      San Jose  ...
3                        0           73  Sporting Goods   Los Angeles  ...
4                        0           73  Sporting Goods        Caguas  ...
...                    ...          ...             ...           ...  ...
180514                   0           45         Fishing      Brooklyn  ...
180515                   1           45         Fishing   Bakersfield  ...
180516                   1           45         Fishing       Bristol  ...
180517                   0           45         Fishing        Caguas  ...
180518                   0           45         Fishing        Caguas  ...

              Order State     Order Status Order Zipcode Product Card Id  \
0         Java Occidental         COMPLETE           NaN            1360
1                Rajastán          PENDING           NaN            1360
2                Rajastán           CLOSED           NaN            1360
3              Queensland         COMPLETE           NaN            1360
4              Queensland  PENDING_PAYMENT           NaN            1360
...                   ...              ...           ...             ...
180514           Shanghái           CLOSED           NaN            1004
180515              Osaka         COMPLETE           NaN            1004
180516  Australia del Sur          PENDING           NaN            1004
180517  Australia del Sur  PENDING_PAYMENT           NaN            1004
180518         Tamil Nadu  PENDING_PAYMENT           NaN            1004

        Product Category Id                               Product Name  \
0                        73                               Smart watch
1                        73                               Smart watch
2                        73                               Smart watch
3                        73                               Smart watch
4                        73                               Smart watch
...                     ...                                        ...
180514                   45  Field & Stream Sportsman 16 Gun Fire Safe
180515                   45  Field & Stream Sportsman 16 Gun Fire Safe
180516                   45  Field & Stream Sportsman 16 Gun Fire Safe
180517                   45  Field & Stream Sportsman 16 Gun Fire Safe
180518                   45  Field & Stream Sportsman 16 Gun Fire Safe

       Product Price Product Status shipping date (DateOrders)   Shipping Mode
0         327.750000              0        2018-03-02 22:56:00  Standard Class
1         327.750000              0            1/18/2018 12:27  Standard Class
2         327.750000              0            1/17/2018 12:06  Standard Class
3         327.750000              0            1/16/2018 11:45  Standard Class
4         327.750000              0            1/15/2018 11:24  Standard Class
...              ...            ...                        ...             ...
180514    399.980011              0             1/20/2016 3:40  Standard Class
180515    399.980011              0             1/19/2016 1:34    Second Class
180516    399.980011              0            1/20/2016 21:00  Standard Class
180517    399.980011              0            1/18/2016 20:18  Standard Class
180518    399.980011              0            1/19/2016 18:54  Standard Class

[180519 rows x 44 columns]

In [11]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Id                           0
Customer Segment                      0
Customer State                        0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [14]:
df.drop("Customer Zipcode",axis = 1)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Java Occidental,COMPLETE,NaN,1360,73,Smart watch,327.750000,0,2018-03-02 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,Rajastán,PENDING,NaN,1360,73,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,Rajastán,CLOSED,NaN,1360,73,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Queensland,COMPLETE,NaN,1360,73,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Queensland,PENDING_PAYMENT,NaN,1360,73,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,Shanghái,CLOSED,NaN,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,Osaka,COMPLETE,NaN,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,Australia del Sur,PENDING,NaN,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,Australia del Sur,PENDING_PAYMENT,NaN,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,Tamil Nadu,PENDING_PAYMENT,NaN,1004,45,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

In [15]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Id', 'Customer Segment', 'Customer State',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Name', 'Product Price', 'Product Status',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [20]:
df.columns = df.columns.str.strip()

In [23]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Id', 'Customer Segment', 'Customer State',
       'Department Id', 'Department Name', 'Market', 'Order City',
       'Order Country', 'Order Customer Id', 'order date (DateOrders)',
       'Order Id', 'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Product Card Id', 'Product Category Id',
       'Product Name', 'Product Price', 'Product Status',
       'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [25]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.columns = df.columns.str.strip().str.lower()

In [30]:
print(df.columns)

Index(['type', 'days for shipping (real)', 'days for shipment (scheduled)',
       'benefit per order', 'sales per customer', 'delivery status',
       'late_delivery_risk', 'category id', 'category name', 'customer city',
       'customer country', 'customer id', 'customer segment', 'customer state',
       'department id', 'department name', 'market', 'order city',
       'order country', 'order customer id', 'order date (dateorders)',
       'order id', 'order item cardprod id', 'order item discount',
       'order item discount rate', 'order item id', 'order item product price',
       'order item profit ratio', 'order item quantity', 'sales',
       'order item total', 'order profit per order', 'order region',
       'order state', 'order status', 'product card id', 'product category id',
       'product name', 'product price', 'product status',
       'shipping date (dateorders)', 'shipping mode'],
      dtype='object')

In [32]:
df.rename(columns={
    'order date (dateorders)': 'order_date',
    'shipping date (dateorders)': 'shipping_date'
}, inplace=True)

In [39]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['shipping_date'] = pd.to_datetime(df['shipping_date'])

df['delivery_days'] = (
    df['shipping_date'] - df['order_date']
).dt.days

In [40]:
df[['order_date', 'shipping_date', 'delivery_days']].head(5)

           order_date       shipping_date  delivery_days
0 2018-01-31 22:56:00 2018-03-02 22:56:00             30
1 2018-01-13 12:27:00 2018-01-18 12:27:00              5
2 2018-01-13 12:06:00 2018-01-17 12:06:00              4
3 2018-01-13 11:45:00 2018-01-16 11:45:00              3
4 2018-01-13 11:24:00 2018-01-15 11:24:00              2

In [41]:
df.to_csv("cleaned_supply_chain.csv", index=False)

In [42]:
import os
print(os.getcwd())

C:\Users\veda